package com.dalvik.pokemonsters.utils

//Params send to fragments
const val PARAM_ITEM_NEWS = "PARAM_ITEM_NEWS"
const val PARAM_ITEM_REGION = "PARAM_ITEM_REGION"
const val PARAM_ITEM_REGION_NAME = "PARAM_ITEM_REGION_NAME"
const val PARAM_ITEM_REGION_SERIE_URL = "PARAM_ITEM_REGION_SERIE_URL"
const val PARAM_ITEM_REGION_TOTAL = "PARAM_ITEM_REGION_TOTAL"
const val PARAM_ITEM_POKEMON_ID = "PARAM_ITEM_POKEMON_ID"
const val PARAM_URL_NEWS = "PARAM_URL_NEWS"
const val PARAM_ITEM_POKEMON_NAME = "PARAM_ITEM_POKEMON_NAME"
const val PARAM_ITEM_POKEMON_SRC = "PARAM_ITEM_POKEMON_SRC"